[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv32i-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tkernel.ld",
    "-Clink-arg=-Map=kernel.map"
]

[build]
target = "riscv32i-unknown-none-elf"

[target.'cfg(all())']
runner = "cargo make run"
